base/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

from base.views import principal, logout_user, ayuda, personalizar, personalizar_modificar,personalizar_eliminar
# para las iamgenes
from django.conf import settings
from django.conf.urls.static import static
# para la gestion de login y contraseña
from django.contrib.auth import views as auth_views
from accounts.views import register
from venta.views import ubicacion_eliminar

urlpatterns = [
    #gestion de login y contraseña
    path('',auth_views.LoginView.as_view(),name='inicio'),
    path('reiniciar/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('reiniciar/enviar',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reiniciar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reiniciar/completo',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('logout/',logout_user,name="logout"),
    path('admin/', admin.site.urls),
    path('inicio/', principal, name="index" ),
    path('inicio-guest/', principal, name="body-login" ),
    path('usuarios/', include('usuario.urls') ),
    path('ventas/', include('venta.urls')),
    path('compras/', include('compra.urls')),
    path('inventarios/',include('inventario.urls')),
    path('templates/partials/', include('accounts.urls')),
    path('account-register/',  views.register, name='Registrarse'),
    path('cerrar-sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('personalizar/', personalizar, name="personalizar"),
    path('personalizar/modificar/<int:pk>/', personalizar_modificar, name="personalizar-modificar"),
    path('base/personalizar/eliminar/<int:pk>/', personalizar_eliminar, name="personalizar-eliminar"),
    path('ayuda/', ayuda, name="help"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from accounts.views import persona_listar,persona_modificar,persona_eliminar
from usuario.views import eps_listar, eps_crear, eps_modificar, eps_eliminar
from usuario.views import turno_listar, turno_crear, turno_modificar, turno_eliminar
from usuario.views import trabajador_listar, trabajador_crear, trabajador_modificar, trabajador_eliminar

urlpatterns = [
    path('persona/', persona_listar, name="persona" ),
    path('persona/modificar/<int:pk>/', persona_modificar, name="persona-modificar" ),
    path('persona/eliminar/<int:pk>/', persona_eliminar, name="persona-eliminar"),
    path('eps/', eps_listar, name="eps" ),
    path('eps/crear/', eps_crear, name="eps-crear" ),
    path('eps/modificar/<int:pk>/', eps_modificar, name="eps-modificar" ),
    path('eps/eliminar/<int:pk>/', eps_eliminar, name="eps-eliminar" ),
    path('turno/', turno_listar, name="turno" ),
    path('turno/crear/', turno_crear, name="turno-crear" ),
    path('turno/modificar/<int:pk>/', turno_modificar, name="turno-modificar" ),
    path('turno/eliminar/<int:pk>/', turno_eliminar, name="turno-eliminar" ),
    path('trabajador/', trabajador_listar, name="trabajador" ),
    path('trabajador/crear/', trabajador_crear, name="trabajador-crear" ),
    path('trabajador/modificar/<int:pk>/', trabajador_modificar, name="trabajador-modificar" ),
    path('trabajador/eliminar/<int:pk>/', trabajador_eliminar, name="trabajador-eliminar" ),

]

usuario/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from safedelete.models import SafeDeleteModel


#Create your models here.


class Eps(SafeDeleteModel):
    nombre=models.CharField(max_length=45,verbose_name="Nombre EPS:")
    class Estado(models.TextChoices):
        ACTIVO='1',_("Activo")
        INACTIVO='0',_("Inactivo")
    estado=models.CharField(max_length=1,choices=Estado.choices,default=Estado.ACTIVO,verbose_name="Estado")
    def __str__(self):
        return "%s "%(self.nombre)
    class Meta:
        verbose_name_plural = "Eps"

class Turno(SafeDeleteModel):
    fecha_ingreso= models.DateTimeField(verbose_name="Fecha de Ingreso", help_text="HH/MM/SS")
    fecha_salida= models.DateTimeField(verbose_name="Fecha de Salida", help_text="HH/MM/SS")
    class Estado(models.TextChoices):
        ACTIVO='1',_("Activo")
        INACTIVO='0',_("Inactivo")
    estado=models.CharField(max_length=1,choices=Estado.choices,default=Estado.ACTIVO,verbose_name="Estado")
    def __str__(self):
        return "%s %s"%(self.fecha_ingreso,self.fecha_salida)
    class Meta:
        verbose_name_plural = "Turnos"

class Trabajador(SafeDeleteModel):
    nombre= models.CharField(max_length=45,verbose_name="Nombre:")
    apellido= models.CharField(max_length=45,verbose_name="Apellido:")
    documento=models.IntegerField(verbose_name="Documento:")
    telefono=models.CharField(max_length=10,verbose_name="Telefono")
    correo=models.CharField(max_length=45,verbose_name="Correo electronico:")
    direccion=models.CharField(max_length=45,verbose_name="Dirección:")
    usuario=models.CharField(max_length=45,verbose_name="Usuario:")
    contrasena=models.CharField(max_length=45,verbose_name="Contraseña:")

    def __str__(self):
        return "%s" % (self.nombre)


    class Estado(models.TextChoices):
        ACTIVO='1',_("Activo")
        INACTIVO='0',_("Inactivo")
    estado=models.CharField(max_length=1,choices=Estado.choices,default=Estado.ACTIVO,verbose_name="Estado")
    turno_trabajador=models.ForeignKey(Turno, on_delete=models.CASCADE,verbose_name="Turno Trabajador")
    eps_trabajador=models.ForeignKey(Eps, on_delete=models.CASCADE,verbose_name="Eps Trabajador")
    def __str__(self):
        return "%s %s %s %s"%(self.turno_trabajador, self.eps_trabajador, self.nombre,self.documento)

    class Meta:
        verbose_name_plural = "Trabajadores"

base/views.py
from django.shortcuts import redirect, render

from usuario.forms import PersonalizarForm, PersonalizarUpdateForm
from usuario.models import  Eps, Turno, Trabajador
from venta.models import Venta, Reserva, Ubicacion
from compra.models import Compra, Detalle_compra, Evento, Proveedor, Personalizacion
from inventario.models import Presentacion, Marca, ConsumoTrabajador, Producto, UnidadMedida
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from compra.models import Personalizacion
@login_required
def principal(request):

    titulo="Bienvenido al Sistema de william"
    personalizar=Personalizacion.objects.all()
    eps=Eps.objects.all().count()
    turno=Turno.objects.all().count()
    trabajador=Trabajador.objects.all().count()
    venta=Venta.objects.all().count()
    reserva=Reserva.objects.all().count()
    ubicacion=Ubicacion.objects.all().count()
    compra=Compra.objects.all().count()
    detalle_compra=Detalle_compra.objects.all().count()
    evento=Evento.objects.all().count()
    proveedor=Proveedor.objects.all().count()
    presentacion=Presentacion.objects.all().count()
    marca=Marca.objects.all().count()
    consumo_trabajador=ConsumoTrabajador.objects.all().count()
    producto=Producto.objects.all().count()
    unidad_medida=UnidadMedida.objects.all().count()
    context={
        "eps": eps,
        "turnos": turno,
        "trabajadores": trabajador,
        "ventas": venta,
        "reservas": reserva,
        "ubicaciones": ubicacion,
        "compras": compra,
        "detalle_compras": detalle_compra,
        "eventos": evento,
        "proveedores": proveedor,
        "productos": producto,
        "presentaciones": presentacion,
        "marcas": marca,
        "unidad_medidas": unidad_medida,
        "consumo_trabajadores": consumo_trabajador,
        "titulo":titulo,
        "personalizar":personalizar
    }
    return render(request, "index.html", context)

def logout_user(request):
    logout(request)
    return redirect('inicio')
def ayuda(request):
    return render(request, "partials/ayuda.html")
def personalizar_modificar(request,pk):
    titulo="Personalizar"
    personalizar= Personalizacion.objects.get(id=pk)
    if request.method== 'POST':
        form= PersonalizarUpdateForm(request.POST, instance=personalizar)
        if form.is_valid():
            form.save()
            messages.success(request, 'La imagen se modifico correctamente.')
            return redirect('personalizar')
    else:
        form= PersonalizarUpdateForm(instance=personalizar)
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request, "personalizar.html",context)

def personalizar_eliminar(request, pk):
    Personalizacion.objects.filter(id=pk).delete()
    messages.success(request,'La imagen se eliminó correctamente.')
    return redirect('personalizar')
def personalizar(request):
    titulo="Personalizar"
    modulo = "base"
    personalizar=Personalizacion.objects.all()
    if request.method== 'POST':
        form= PersonalizarForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request,'Se agregó la imagen correctamente.')
            return redirect('personalizar')
        else:
            messages.error(request, 'El formulario tiene errores.')
    else:
        form= PersonalizarForm()
    context={
        "titulo":titulo,
        "form":form,
        "modulo":modulo,
        "personalizar":personalizar,
    }
    return render(request, "partials/personalizar.html",context)

usuario/views.py
from django.shortcuts import render, redirect
from usuario.models import Eps
from usuario.models import Turno
from usuario.models import Trabajador
from usuario.forms import EpsForm,EpsUpdateForm,TurnoForm,TurnoUpdateForm,TrabajadorForm,TrabajadorUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required


# Create your views here.

#views de tabla eps
@login_required
@permission_required("usuario.add_eps", login_url="index")
def eps_crear(request):
    titulo="Eps"
    if request.method== 'POST':
        form= EpsForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'La eps se creo correctamente.')
            return redirect('eps')
        else:
            messages.error(request, 'El formulario tiene errores.')
    else:
        form= EpsForm()
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request, "usuarios/eps/crear.html", context)
@login_required
def eps_listar(request):
    # Verificar si el usuario tiene permisos
    if not request.user.has_perm("usuario.view_eps"):
        messages.error(request, "No tienes permisos para acceder a Eps.")
        return redirect("index")  # Redirige al usuario al índice
    titulo="Eps"
    modulo="Usuarios"
    eps= Eps.objects.all()
    context={
        "titulo":titulo,
        "modulo":modulo,
        "eps":eps
    }
    return render(request, "usuarios/eps/listar.html", context)
@login_required
@permission_required("usuario.change_eps", login_url="index")
def eps_modificar(request,pk):
    titulo="Eps"
    eps= Eps.objects.get(id=pk)
    if request.method== 'POST':
        form= EpsUpdateForm(request.POST, instance=eps)
        if form.is_valid():
            form.save()
            messages.success(request, 'El formulario se modifico correctamente.')
            return redirect('eps')
    else:
        form= EpsUpdateForm(instance=eps)
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request, "usuarios/eps/modificar.html", context)
@login_required
@permission_required("usuario.delete_eps", login_url="index")
def eps_eliminar(request,pk):
    eps= Eps.objects.filter(id=pk)
    eps.update(
        estado="0"
    )
    messages.success(request,'La eps se elimino correctamente.')
    return redirect('eps')

#views de tabla turno
@login_required
def turno_crear(request):
    # Verificar si el usuario tiene permisos
    if not request.user.has_perm("usuario.add_turno"):
        messages.error(request, "No tienes permisos para Crear un Turno.")
        return redirect("turno")  # Redirige al usuario al índice
    titulo="Turno"
    if request.method== 'POST':
        form= TurnoForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'El turno se creo correctamente.')
            return redirect('turno')
        else:
            messages.error(request, 'El formulario tiene errores.')
    else:
        form= TurnoForm()
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request, "usuarios/turno/crear.html", context)
@login_required
def turno_listar(request):
    # Verificar si el usuario tiene permisos
    if not request.user.has_perm("usuario.view_turno"):
        messages.error(request, "No tienes permisos para acceder a Turno.")
        return redirect("index")  # Redirige al usuario al índice
    titulo="Turno"
    modulo="Usuarios"
    turnos= Turno.objects.all()
    context={
        "titulo":titulo,
        "modulo":modulo,
        "turnos":turnos
    }
    return render(request, "usuarios/turno/listar.html", context)
@login_required
def turno_modificar(request,pk):
    # Verificar si el usuario tiene permisos
    if not request.user.has_perm("usuario.change_turno"):
        messages.error(request, "No tienes permisos para modificar el Turno.")
        return redirect("turno")  # Redirige al usuario al índice
    titulo="Turno"
    turno= Turno.objects.get(id=pk)
    if request.method== 'POST':
        form= TurnoUpdateForm(request.POST, instance=turno)
        if form.is_valid():
            form.save()
            messages.success(request, 'El formulario se modificado correctamente.')
            return redirect('turno')
    else:
        form= TurnoUpdateForm(instance=turno)
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request, "usuarios/turno/modificar.html", context)
@login_required
def turno_eliminar(request,pk):
    # Verificar si el usuario tiene permisos
    if not request.user.has_perm("usuario.delete_turno"):
        messages.error(request, "No tienes permisos para eliminar el Turno.")
        return redirect("turno")  # Redirige al usuario al índice
    turno= Turno.objects.filter(id=pk)
    turno.update(
        estado="0"
    )
    messages.success(request,'El turno se elimino correctamente.')
    return redirect('turno')

#views de tabla trabajador
@login_required
@permission_required("usuario.add_trabajador", login_url="index")
def trabajador_crear(request):
    titulo="Trabajador"
    if request.method== 'POST':
        form= TrabajadorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'El trabajador se creo correctamente.')
            return redirect('trabajador')
        else:
            messages.error(request, 'El formulario tiene errores.')
    else:
        form= TrabajadorForm()
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request, "usuarios/trabajador/crear.html", context)
@login_required
def trabajador_listar(request):
    # Verificar si el usuario tiene permisos
    if not request.user.has_perm("usuario.view_trabajador"):
        messages.error(request, "No tienes permisos para acceder a los datos del Trabajador.")
        return redirect("index")  # Redirige al usuario al índice
    titulo="Trabajador"
    modulo="Usuarios"
    trabajadores= Trabajador.objects.all()
    context={
        "titulo":titulo,
        "modulo":modulo,
        "trabajadores":trabajadores
    }
    return render(request, "usuarios/trabajador/listar.html", context)
@login_required
@permission_required("usuario.change_trabajador", login_url="index")
def trabajador_modificar(request,pk):
    titulo="Trabajador"
    trabajador= Trabajador.objects.get(id=pk)
    if request.method== 'POST':
        form= TrabajadorUpdateForm(request.POST, instance=trabajador)
        if form.is_valid():
            form.save()
            messages.success(request, 'El formulario se modificado correctamente.')
            return redirect('trabajador')
    else:
        form= TrabajadorUpdateForm(instance=trabajador)
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request, "usuarios/trabajador/modificar.html", context)
@login_required
@permission_required("usuario.delete_trabajador", login_url="index")
def trabajador_eliminar(request,pk):
    trabajador= Trabajador.objects.filter(id=pk)
    trabajador.update(
        estado="0"
    )
    messages.success(request,'El trabajador se elimino correctamente.')
    return redirect('trabajador')

base/templates/usuarios/turno/crear.html
{% extends 'partials/body.html' %}
{% block contenido %}
    <div class="wrapper">
        <div class="card glass-card">
            <div class="card-header text-black-500">
                Crear {{ titulo }}
            </div>
            <div class="card-body">
                <form class="row g-3" action="" method="POST">
                    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);"
                         aria-label="breadcrumb" class="d-flex justify-content-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'persona' %}">{{ titulo }}</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Crear {{ titulo }}</li>
                        </ol>
                    </nav>

                    {% csrf_token %}
                    {% for field in form %}
                        <div class="col-md-6">
                            <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <div class="col-12">
                        <input type="submit" class="btn color_dorado w-25" value="Agregar {{ titulo }}"/>
                        <a href="{% url 'turno' %}" class="btn color_dorado w-25">Volver</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock contenido %}

base/templates/usuarios/turno/listar.html
{% extends 'partials/body.html' %}
{% load bootstrap_icons %}
{% block contenido %}
    <div class="wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card glass-card">
                            <div class="card-header d-flex justify-content-between align-items-center">
                                <h3 class="card-title"> {{ titulo }} </h3>
                                <a href="{% url 'turno-crear' %}" class="btn color_dorado w-25">Crear {{ titulo }}</a>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="container">
                                    <div class="row">
                                        <div class="col">
                                            <div class="d-flex justify-content-end">
                                                <ol class="breadcrumb float-sm-right">
                                                    <li class="breadcrumb-item"><a
                                                            href="{% url 'index' %}">Inicio</a></li>
                                                    <li class="breadcrumb-item active"><a
                                                            href="{% url 'turno' %}">{{ titulo }}</a></li>
                                                    <li class="breadcrumb-item active">{{ titulo }} </li>
                                                </ol>
                                            </div>
                                        </div>
                                    </div>
                                    <table id="example1" class="table table-bordered table-striped table-dark">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Fecha de Ingreso</th>
                                            <th>Fecha de Salida</th>
                                            <th class="notexport">Estado</th>
                                            <th class="notexport">Acciones</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for turno in turnos %}
                                            {% if turno.estado != "0" %}
                                                <tr>
                                                    <td>{{ turno.id }}
                                                    <td>{{ turno.fecha_ingreso }}</td>
                                                    <td>{{ turno.fecha_salida }}</td>
                                                    <td>{{ turno.get_estado_display }}</td>
                                                    <td>
                                                        <button type="button" data-cafe-bar="{{ turno.id }}"
                                                                class="btnEliminar btn btn-danger"
                                                                data-bs-toggle="modal" data-bs-target="#modalConf">
                                                            {% bs_icon 'trash' %}
                                                        </button>
                                                        <a class="btn btn-primary"
                                                               href="{% url 'turno-modificar' user.id %}">
                                                                {% bs_icon 'pencil-square' %}
                                                            </a>
                                                    </td>
                                                </tr>
                                            {% endif %} {% endfor %}
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>ID</th>
                                            <th>Fecha de Ingreso</th>
                                            <th>Fecha de Salida</th>
                                            <th class="notexport">Estado</th>
                                            <th class="notexport">Acciones</th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
{% endblock contenido %}

base/templates/usuarios/turno/modificar.html
{% extends 'partials/body.html' %}
{% block contenido %}
    <div class="wrapper">
        <div class="card glass-card">
            <div class="card-header text-black-500">
                Modificar {{ titulo }}
            </div>
            <div class="card-body">
                <form class="row g-3" action="" method="POST">
                    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);"
                         aria-label="breadcrumb" class="d-flex justify-content-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'turno' %}">{{ titulo }}</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Modificar {{ titulo }}</li>
                        </ol>
                    </nav>

                    {% csrf_token %}
                    {% for field in form %}
                        <div class="col-md-6">
                            <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <div class="col-12">
                        <input type="submit" class="btn color_dorado w-25" value="Modificar {{ titulo }}"/>
                        <a href="{% url 'turno' %}" class="btn color_dorado w-25">Volver</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock contenido %}