base/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

from base.views import principal, logout_user, ayuda, personalizar, personalizar_modificar,personalizar_eliminar
# para las iamgenes
from django.conf import settings
from django.conf.urls.static import static
# para la gestion de login y contraseña
from django.contrib.auth import views as auth_views
from accounts.views import register
from venta.views import ubicacion_eliminar

urlpatterns = [
    #gestion de login y contraseña
    path('',auth_views.LoginView.as_view(),name='inicio'),
    path('reiniciar/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('reiniciar/enviar',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reiniciar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reiniciar/completo',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('logout/',logout_user,name="logout"),
    path('admin/', admin.site.urls),
    path('inicio/', principal, name="index" ),
    path('inicio-guest/', principal, name="body-login" ),
    path('usuarios/', include('usuario.urls') ),
    path('ventas/', include('venta.urls')),
    path('compras/', include('compra.urls')),
    path('inventarios/',include('inventario.urls')),
    path('templates/partials/', include('accounts.urls')),
    path('account-register/',  views.register, name='Registrarse'),
    path('cerrar-sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('personalizar/', personalizar, name="personalizar"),
    path('personalizar/modificar/<int:pk>/', personalizar_modificar, name="personalizar-modificar"),
    path('base/personalizar/eliminar/<int:pk>/', personalizar_eliminar, name="personalizar-eliminar"),
    path('ayuda/', ayuda, name="help"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compra/urls.py
from django.urls import path
from compra.views import compra_crear,compra_listar,compra_modificar,compra_eliminar,eliminar_detalle_compra
from compra.views import compra_finalizar
from compra.views import detalle_compra_listar, detalle_compra_crear, detalle_compra_modificar, detalle_compra_eliminar
from compra.views import evento_listar, evento_crear, evento_modificar, evento_eliminar , ver_detalle
from compra.views import proveedor_listar, proveedor_crear, proveedor_modificar, proveedor_eliminar

urlpatterns = [
    path('compra/', compra_listar, name="compra"),
    path('compra/crear/', compra_crear, name="compra-crear"),
    path('compra/modificar/<int:pk>/', compra_modificar, name="compra-modificar"),
    path('compra/eliminar/<int:pk>/', compra_eliminar, name="compra-eliminar"),
    path('detalle_compra/<int:pk>', detalle_compra_listar, name="detalle_compra"),
    path('detalle_compra/crear/', detalle_compra_crear, name="detalle_compra-crear"),
    path('detalle_compra/modificar/<int:pk>/', detalle_compra_modificar, name="detalle_compra-modificar"),
    path('detalle_compra/eliminar/<int:pk>/', detalle_compra_eliminar, name="detalle_compra-eliminar"),
    path('evento/', evento_listar, name="evento"),
    path('evento/crear/', evento_crear, name="evento-crear"),
    path('evento/modificar/<int:pk>/', evento_modificar, name="evento-modificar"),
    path('evento/eliminar/<int:pk>/', evento_eliminar, name="evento-eliminar"),
    path('proveedor/', proveedor_listar, name="proveedor"),
    path('proveedor/crear/', proveedor_crear, name="proveedor-crear"),
    path('proveedor/modificar/<int:pk>/', proveedor_modificar, name="proveedor-modificar"),
    path('proveedor/eliminar/<int:pk>/', proveedor_eliminar, name="proveedor-eliminar"),
    path('ver_detalle/<int:pk>/', ver_detalle ,name='ver_detalle'),
    path('compra/detalle_compra/', detalle_compra_listar ,name='detalle-compras'),
    path('compra_finalizar/<int:pk>/', compra_finalizar ,name='compra_finalizar'),
    path('eliminar_detalle_compra/<int:pk>/', eliminar_detalle_compra ,name='eliminar_detalle_compra'),
]

compra/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from inventario.models import Producto
from safedelete.models import SafeDeleteModel

# Create your models here.

class Proveedor(SafeDeleteModel):
    class Tipo_identificacion(models.TextChoices):
        CEDULA = 'CC', _("Cédula")
        CEDULA_EXTRANJERIA = 'CE', _("Cédula de Extranjería")

    tipo_identificacion = models.CharField(max_length=2, choices=Tipo_identificacion.choices,
                                           verbose_name="Tipo de Identificación")
    nombre_proveedor = models.CharField(max_length=45, verbose_name="Nombre Proveedor")
    apellido_proveedor = models.CharField(max_length=45, verbose_name="Apellido Proveedor")
    telefono = models.CharField(max_length=10, verbose_name="Teléfono")
    correo_proveedor = models.CharField(max_length=50, verbose_name="Correo Proveedor")
    direccion_proveedor = models.CharField(max_length=50, verbose_name="Dirección Proveedor")

    class Estado_proveedor(models.TextChoices):
        ACTIVO = '1', _("Activo")
        INACTIVO = '0', _("Inactivo")

    estado_proveedor = models.CharField(max_length=1, choices=Estado_proveedor.choices, default=Estado_proveedor.ACTIVO,verbose_name="Estado Proveedor")

    def clean(self):
        self.nombre_proveedor = self.nombre_proveedor.title()
        self.apellido_proveedor = self.apellido_proveedor.title()
        self.correo_proveedor = self.correo_proveedor.lower()

    def _str_(self):
        return "%s %s" % (self.nombre_proveedor, self.apellido_proveedor)

    class Meta:
        verbose_name_plural = "Proveedores"


from django.db import models
from django.utils.translation import gettext as _
from safedelete.models import SafeDeleteModel


class Compra(SafeDeleteModel):
    fecha_compra = models.DateField(verbose_name="Fecha Compra", help_text="MM/DD/AAAA", auto_now_add=True)

    class Estado_compra(models.TextChoices):
        ACTIVO = '1', _("Activo")
        INACTIVO = '0', _("Inactivo")

    estado_compra = models.CharField(
        max_length=1,
        choices=Estado_compra.choices,
        default=Estado_compra.ACTIVO,
        verbose_name="Estado Evento"
    )

    id_proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE, verbose_name="Nombre Proveedor" )
    def __str__(self):
        return "%s %s" % (self.id_proveedor, self.fecha_compra)

    class Meta:
        verbose_name_plural = "Compras"


class Detalle_compra(SafeDeleteModel):
    compra=models.ForeignKey(Compra, on_delete=models.CASCADE, verbose_name="compra")
    cantidad_producto = models.IntegerField(verbose_name="Cantidad Producto")
    nombre_producto = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Nombre Producto")

    def _str_(self):
        return "%s %s" % (self.cantidad_producto)

    class Meta:
        verbose_name_plural = "detalles_compras"






class Evento(SafeDeleteModel):
    nombre_evento = models.CharField(max_length=45, verbose_name="Nombre Evento")
    fecha_inicio = models.DateField(verbose_name="Fecha Incio Evento", help_text="MM/DD/AAAA")
    fecha_fin = models.DateField(verbose_name="Fecha Fin Evento", help_text="MM/DD/AAAA")
    descripcion = models.CharField(max_length=200, verbose_name="Descripción Evento")


    class Estado_evento(models.TextChoices):
        ACTIVO = '1', _("Activo")
        INACTIVO = '0', _("Inactivo")

    estado_evento = models.CharField(max_length=1, choices=Estado_evento.choices, default=Estado_evento.ACTIVO,
                                     verbose_name="Estado Evento")
    id_compra = models.ForeignKey(Compra, on_delete=models.CASCADE, verbose_name="Fecha de Compra")

    def _str_(self):
        return "%s" % (self.id_compra)

class Personalizacion(SafeDeleteModel):
    nombre = models.CharField(max_length=45, verbose_name="Nombre")
    descripcion = models.CharField(max_length=45, verbose_name="Descripción")
    fecha = models.DateField(verbose_name="Fecha", help_text="MM/DD/AAAA", auto_now=True)
    imagen = models.ImageField(upload_to="productos/", blank=True, null=True,default="productos/default-producto.png")
    class Estado(models.TextChoices):
        ACTIVO = '1', _("Activo")
        INACTIVO = '0', _("Inactivo")
    estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO,
                                         verbose_name="Estado")
    def _str_(self):
        return "%s" % (self.nombre)

compra/forms.py
from django import forms
from django.forms import ModelForm, widgets
from compra.models import Compra, Detalle_compra, Evento, Proveedor


class CompraForm(ModelForm):
    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control small-input'

    class Meta:
        model = Compra
        fields = "__all__"
        widgets = {
            'fecha_compra': widgets.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
        }
        exclude = ["estado",]


class CompraUpdateForm(ModelForm):
    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control small-input'

    class Meta:
        model = Compra
        fields = "__all__"
        exclude = ["estado",]


class Detalle_compraForm(ModelForm):
    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control small-input'

    class Meta:
        model = Detalle_compra
        fields = "__all__"
        exclude = ["estado"]


class Detalle_compraUpdateForm(ModelForm):
    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control small-input'

    class Meta:
        model = Detalle_compra
        fields = "__all__"


class EventoForm(ModelForm):
    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control small-input'

    class Meta:
        model = Evento
        fields = "__all__"
        widgets = {
            'fecha_inicio': widgets.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
            'fecha_fin': widgets.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
        }
        exclude = ('estado_evento',)


class EventoUpdateForm(ModelForm):
    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control small-input'

    class Meta:
        model = Evento
        fields = "__all__"
        exclude = ('estado_evento',)


class ProveedorForm(ModelForm):
    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control small-input'

    class Meta:
        model = Proveedor
        fields = "__all__"
        exclude = ["estado_proveedor", ]


class ProveedorUpdateForm(ModelForm):
    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control small-input'

    class Meta:
        model = Proveedor
        fields = "__all__"
        exclude = [" tipo_identificacion", "estado_proveedor"]

base/views.py
from django.shortcuts import redirect, render

from usuario.forms import PersonalizarForm, PersonalizarUpdateForm
from usuario.models import  Eps, Turno, Trabajador
from venta.models import Venta, Reserva, Ubicacion
from compra.models import Compra, Detalle_compra, Evento, Proveedor, Personalizacion
from inventario.models import Presentacion, Marca, ConsumoTrabajador, Producto, UnidadMedida
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from compra.models import Personalizacion
@login_required
def principal(request):

    titulo="Bienvenido al Sistema de william"
    personalizar=Personalizacion.objects.all()
    eps=Eps.objects.all().count()
    turno=Turno.objects.all().count()
    trabajador=Trabajador.objects.all().count()
    venta=Venta.objects.all().count()
    reserva=Reserva.objects.all().count()
    ubicacion=Ubicacion.objects.all().count()
    compra=Compra.objects.all().count()
    detalle_compra=Detalle_compra.objects.all().count()
    evento=Evento.objects.all().count()
    proveedor=Proveedor.objects.all().count()
    presentacion=Presentacion.objects.all().count()
    marca=Marca.objects.all().count()
    consumo_trabajador=ConsumoTrabajador.objects.all().count()
    producto=Producto.objects.all().count()
    unidad_medida=UnidadMedida.objects.all().count()
    context={
        "eps": eps,
        "turnos": turno,
        "trabajadores": trabajador,
        "ventas": venta,
        "reservas": reserva,
        "ubicaciones": ubicacion,
        "compras": compra,
        "detalle_compras": detalle_compra,
        "eventos": evento,
        "proveedores": proveedor,
        "productos": producto,
        "presentaciones": presentacion,
        "marcas": marca,
        "unidad_medidas": unidad_medida,
        "consumo_trabajadores": consumo_trabajador,
        "titulo":titulo,
        "personalizar":personalizar
    }
    return render(request, "index.html", context)

def logout_user(request):
    logout(request)
    return redirect('inicio')
def ayuda(request):
    return render(request, "partials/ayuda.html")
def personalizar_modificar(request,pk):
    titulo="Personalizar"
    personalizar= Personalizacion.objects.get(id=pk)
    if request.method== 'POST':
        form= PersonalizarUpdateForm(request.POST, instance=personalizar)
        if form.is_valid():
            form.save()
            messages.success(request, 'La imagen se modifico correctamente.')
            return redirect('personalizar')
    else:
        form= PersonalizarUpdateForm(instance=personalizar)
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request, "personalizar.html",context)

def personalizar_eliminar(request, pk):
    Personalizacion.objects.filter(id=pk).delete()
    messages.success(request,'La imagen se eliminó correctamente.')
    return redirect('personalizar')
def personalizar(request):
    titulo="Personalizar"
    modulo = "base"
    personalizar=Personalizacion.objects.all()
    if request.method== 'POST':
        form= PersonalizarForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request,'Se agregó la imagen correctamente.')
            return redirect('personalizar')
        else:
            messages.error(request, 'El formulario tiene errores.')
    else:
        form= PersonalizarForm()
    context={
        "titulo":titulo,
        "form":form,
        "modulo":modulo,
        "personalizar":personalizar,
    }
    return render(request, "partials/personalizar.html",context)

base/templates/compras/evento/crear.html
{% extends 'partials/body.html' %}
{% block contenido %}
    <div class="wrapper">
        <div class="card glass-card">
            <div class="card-header text-black-500">
                Crear {{ titulo }}
            </div>
            <div class="card-body">
                <form name="frmCrearEvento" class="row g-3" action="" method="POST">
                    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);"
                         aria-label="breadcrumb" class="d-flex justify-content-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'evento' %}">{{ titulo }}</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Crear {{ titulo }}</li>
                        </ol>
                    </nav>

                    {% csrf_token %}
                    {% for field in form %}
                        <div class="col-md-6">
                            <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <div class="col-12">
                        <input type="submit" class="btn color_dorado w-25" value="Agregar {{ titulo }}"/>
                        <a href="{% url 'evento' %}" class="btn color_dorado w-25">Volver</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock contenido %}

base/templates/compras/evento/listar.html
{% extends 'partials/body.html' %}
{% load bootstrap_icons %}
{% block contenido %}
    <div class="wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card glass-card">
                            <div class="card-header d-flex justify-content-between align-items-center">
                                <h3 class="card-title"> {{ titulo }} </h3>
                                <a href="{% url 'evento-crear' %}" class="btn color_dorado w-25">Crear {{ titulo }}</a>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="container">
                                    <div class="row">
                                        <div class="col">
                                            <div class="d-flex justify-content-end">
                                                <ol class="breadcrumb float-sm-right">
                                                    <li class="breadcrumb-item"><a
                                                            href="{% url 'index' %}">Inicio</a></li>
                                                    <li class="breadcrumb-item active"><a
                                                            href="{% url 'evento' %}">{{ titulo }}</a></li>
                                                    <li class="breadcrumb-item active">{{ titulo }} </li>
                                                </ol>
                                            </div>
                                        </div>
                                    </div>
                                    <table id="example1" class="table table-bordered table-striped table-dark">
                                        <thead>
                                        <tr>
                                            <th>Nombre Del Evento</th>
                                            <th>Fecha Incio Evento</th>
                                            <th>Fecha Fin Evento</th>
                                            <th>Descrpción Del Evento</th>
                                            <th class="notexport">Estado Del Evento</th>
                                            <th>Fecha de compra</th>
                                            <th class="notexport">Acciones</th>


                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for evento in eventos %} {% if evento.estado_evento != "0" %}

                                            <tr>
                                                <td>{{ evento.nombre_evento }}</td>
                                                <td>{{ evento.fecha_inicio }}</td>
                                                <td>{{ evento.fecha_fin }}</td>
                                                <td>{{ evento.descripcion }}</td>
                                                <td>{{ evento.get_estado_evento_display }}</td>
                                                <td>{{ evento.id_compra.fecha_compra }}</td>

                                                <td>
                                                    <button type="button" data-cafe-bar="{{ evento.id }}"
                                                            class="btnEliminar btn btn-danger"
                                                            data-bs-toggle="modal" data-bs-target="#modalConf">
                                                        {% bs_icon 'trash' %}
                                                    </button>
                                                    <a class="btn btn-primary"
                                                               href="{% url 'persona-modificar' user.id %}">
                                                                {% bs_icon 'pencil-square' %}
                                                            </a>
                                                </td>
                                            </tr>
                                        {% endif %} {% endfor %}
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>Nombre Del Evento</th>
                                            <th>Fecha Incio Evento</th>
                                            <th>Fecha Fin Evento</th>
                                            <th>Descrpción Del Evento</th>
                                            <th class="notexport">Estado Del Evento</th>
                                            <th>Fecha de compra</th>
                                            <th class="notexport">Acciones</th>

                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
{% endblock contenido %}

base/templates/compras/evento/modificar.html
{% extends 'partials/body.html' %}
{% block contenido %}
    <div class="wrapper">
        <div class="card glass-card">
            <div class="card-header text-black-500">
                Modificar {{ titulo }}
            </div>
            <div class="card-body">
                <form class="row g-3" action="" method="POST">
                    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);"
                         aria-label="breadcrumb" class="d-flex justify-content-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'evento' %}">{{ titulo }}</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Modificar {{ titulo }}</li>
                        </ol>
                    </nav>

                    {% csrf_token %}
                    {% for field in form %}
                        <div class="col-md-6">
                            <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <div class="col-12">
                        <input type="submit" class="btn color_dorado w-25" value="Modificar {{ titulo }}"/>
                        <a href="{% url 'evento' %}" class="btn color_dorado w-25">Volver</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock contenido %}